### ISSUE TITLE
Please share a working nginx site reverse-proxy conf file for https://github.com/esmero/archipelago-deployment/blob/1.3.0/docs/ubuntu.md

### ISSUE THREAD

**Issue by fishfree** [esmero/archipelago-deployment-live#119]
In my server, there is already a running Nginx servce in the host. I also successfully run Archipelago containers according to [the doc](https://github.com/esmero/archipelago-deployment/blob/1.3.0/docs/ubuntu.md). 
So would you please share a working reverse proxy conf file for the running containers?  I cannot figure it out according to [the archipelago-deployment-live nginx.conf file](https://github.com/esmero/archipelago-deployment-live/blob/1.3.0/config_storage/nginxconfig/conf.d/nginx.conf).
Many thanks!

**Comment by DiegoPino** [comment]
@fishfree we don't provide that type of deployment or examples bc the number of combinations we would have to cover would make maintaining one good way/safe and replicable way of deploying impossible. But you can give it a try, might not be so hard. You do need to have some system admin knowledge though. Basically, you will need to:
- Use/copy/that same NGINX.conf file and put it for this specific host in your host level NGNIX.
- Modify : https://github.com/esmero/archipelago-deployment-live/blob/1.3.0/config_storage/nginxconfig/conf.d/nginx.conf#L12 and point it to a "host" accessible path (basically the path to the archipelago deployment folder 
- Change this to the real domain (fixed) that you will have instead of using our Docker level environments:
https://github.com/esmero/archipelago-deployment-live/blob/81a00413bfb9cf935dafb7c8fb6197049be57b2a/config_storage/nginxconfig/conf.d/nginx.conf#L7-L9
- Change any entry that refers to esmero-php or esmero-cantaloupe bc those are not real host names at the HOST level, you can use 127.0.0.1:PORT, like here https://github.com/esmero/archipelago-deployment-live/blob/1.3.0/config_storage/nginxconfig/conf.d/nginx.conf#L2 and https://github.com/esmero/archipelago-deployment-live/blob/1.3.0/config_storage/nginxconfig/conf.d/nginx.conf#L111
- Disable/remove the nginx container (web) from the docker-compose.
- Make sure that you expose in the docker-compose esmero-php (php) to 127.0.0.1 under port 9000. 
- Add Firewalls, externals, docker-compose configs (network) etc so nobody other than your HOST level nginx can access 127.0.0.1:9000

Try, debug, test.

As said, if you go this way I can only hint you in the right direction but can't support the use case officially as part of our releases. Good luck

**Comment by fishfree** [comment]
@DiegoPino Thank you very much. I will try later.

**Comment by DiegoPino** [comment]
Will close this one. Thanks
